odin1_ros2_driver:
  ros__parameters:
    streamctrl: 1
    sendrgb: 1
    sendimu: 1
    sendodom: 1
    senddtof: 1
    sendcloudslam: 1
    sendcloudrender: 0
    sendrgbcompressed: 1
    senddepth: 0
    recorddata: 0
    custom_map_mode: 0    # 0: Odometry mode 1: SLAM mode 2: Relocalization mode

